---
name: Bug report
description: Create a report to help us improve and fix bugs
labels: [ "Status: Waiting", "Type: Bug" ]
---
body:
- type: textarea
  attributes:
    label: Expected behavior
    description: What you expected to see.
  validations:
    required: true
- type: textarea
  attributes:
    label: Observed/Actual behavior
    description: What you actually saw.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps/models to reproduce
    description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue.
  validations:
    required: true
- type: textarea
  attributes:
    label: Other
    description: |
      Please include other helpful information below.
      The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
  validations:
      required: false
