name: UneasyVanilla Bug report
description: Create a report to help us improve and fix bugs
title: "[UneasyVanilla_Bug]: "
labels: [ "Server: UneasyVanilla", "Status: Waiting", "Type: Bug", "Version: 1.18" ]
body:
- type: textarea
  id: Expected-behavior
  attributes:
    label: Expected behavior
    description: What you expected to see.
  validations:
    required: true
- type: textarea
  id: Observed-Actual-behavior
  attributes:
    label: Observed/Actual behavior
    description: What you actually saw.
  validations:
    required: true
- type: textarea
  id: Steps-to-reproduce
  attributes:
    label: Steps/models to reproduce
    description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue.
  validations:
    required: true
- type: textarea
  id: Other
  attributes:
    label: Other
    description: The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
  validations:
    required: false
